steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: 'c:/Master_Details_Functionality/mta.jar'
  neoDeploy:
    neoHome: 'C:/neo'
    neo:
      credentialsId: 'NEO'
      account: p2001269540trial
      host: hanatrial.ondemand.com
