steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: 'c:/mta.jar'
   neoDeploy script: this, source: 'path/to/archiveFile.mtar', neo: [credentialsId: 'NEO', host: hanatrial.ondemand.com]
   neoDeploy:
    neoHome: 'C:/neo'
    deployMode: mta
    neo:
      credentialsId: 'NEO'
      account: p2001269540trial
      host: hanatrial.ondemand.com
